/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.7.0
 * Product:       sen66
 * Model-Version: 1.7.0
 */
/*
 * Copyright (c) 2026, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include <Arduino.h>
#include <SensirionI2cSen66.h>
#include <Wire.h>

// macro definitions
// make sure that we use the proper definition of NO_ERROR
#ifdef NO_ERROR
#undef NO_ERROR
#endif
#define NO_ERROR 0

SensirionI2cSen66 sensor;

static char errorMessage[64];
static int16_t error;

void setup() {

    Serial.begin(115200);
    while (!Serial) {
        delay(100);
    }
    Wire.begin();
    sensor.begin(Wire, SEN66_I2C_ADDR_6B);

    error = sensor.stopMeasurement();
    if (error != NO_ERROR) {
        Serial.print("stop measurement not successful");
        Serial.println();
    }

    delay(50);
    error = sensor.startContinuousMeasurement();
    if (error != NO_ERROR) {
        Serial.print("stop measurement not successful");
        Serial.println();
    }

    delay(1000);
}

void loop() {

    uint8_t padding = 0;
    bool dataReady = false;
    int16_t rawHumidity = 0;
    int16_t rawTemperature = 0;
    uint16_t rawVOC = 0;
    uint16_t rawNOx = 0;
    uint16_t rawCO2 = 0;

    error = sensor.getDataReady(padding, dataReady);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute getDataReady(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    if (dataReady) {
        //
        // Readout raw data from the sensor
        error = sensor.readMeasuredRawValues(rawHumidity, rawTemperature,
                                             rawVOC, rawNOx, rawCO2);
        if (error != NO_ERROR) {
            Serial.print("Error trying to execute readMeasuredRawValues(): ");
            errorToString(error, errorMessage, sizeof errorMessage);
            Serial.println(errorMessage);
            return;
        }
        Serial.print("Raw humidity: ");
        Serial.print(rawHumidity);
        Serial.println();
        Serial.print("Raw temperature: ");
        Serial.print(rawTemperature);
        Serial.println();
        Serial.print("Raw VOC index: ");
        Serial.print(rawVOC);
        Serial.println();
        Serial.print("Raw NOX index: ");
        Serial.print(rawNOx);
        Serial.println();
        Serial.print("Raw CO₂: ");
        Serial.print(rawCO2);
        Serial.println();
    }
}
