/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.7.0
 * Product:       sen66
 * Model-Version: 1.7.1
 */
/*
 * Copyright (c) 2026, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include <Arduino.h>
#include <SensirionI2cSen66.h>
#include <Wire.h>

// macro definitions
// make sure that we use the proper definition of NO_ERROR
#ifdef NO_ERROR
#undef NO_ERROR
#endif
#define NO_ERROR 0

SensirionI2cSen66 sensor;

static char errorMessage[64];
static int16_t error;

void setup() {

    Serial.begin(115200);
    while (!Serial) {
        delay(100);
    }
    Wire.begin();
    sensor.begin(Wire, SEN66_I2C_ADDR_6B);

    error = sensor.stopMeasurement();
    if (error != NO_ERROR) {
        Serial.print("stop measurement not successful");
        Serial.println();
    }

    delay(50);
    //
    // Set the temperature offset parameters:
    // offset = -400
    // slope = 0.02 * 1000
    // time_constant = 800
    // slot = 0
    error = sensor.setTemperatureOffsetParameters(-400, 20, 800, 0);
    if (error != NO_ERROR) {
        Serial.print("stop measurement not successful");
        Serial.println();
    }

    error = sensor.startContinuousMeasurement();
    if (error != NO_ERROR) {
        Serial.print("stop measurement not successful");
        Serial.println();
    }

    delay(1000);
}

void loop() {

    uint8_t padding = 0;
    bool dataReady = false;
    uint16_t massConcentrationPm1p0 = 0;
    uint16_t massConcentrationPm2p5 = 0;
    uint16_t massConcentrationPm4p0 = 0;
    uint16_t massConcentrationPm10p0 = 0;
    int16_t ambientHumidity = 0;
    int16_t ambientTemperature = 0;
    int16_t vOCIndex = 0;
    int16_t nOxIndex = 0;
    uint16_t cO2 = 0;

    error = sensor.getDataReady(padding, dataReady);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute getDataReady(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    if (dataReady) {
        //
        // Readout data from the sensor
        error = sensor.readMeasuredValuesAsIntegers(
            massConcentrationPm1p0, massConcentrationPm2p5,
            massConcentrationPm4p0, massConcentrationPm10p0, ambientHumidity,
            ambientTemperature, vOCIndex, nOxIndex, cO2);
        if (error != NO_ERROR) {
            Serial.print(
                "Error trying to execute readMeasuredValuesAsIntegers(): ");
            errorToString(error, errorMessage, sizeof errorMessage);
            Serial.println(errorMessage);
            return;
        }
        Serial.print("Mass concentration pm1p0 [µg/m³]: ");
        Serial.print(massConcentrationPm1p0 / 10.0);
        Serial.println();
        Serial.print("Mass concentration pm2p5 [µg/m³]: ");
        Serial.print(massConcentrationPm2p5 / 10.0);
        Serial.println();
        Serial.print("Mass concentration pm4p0 [µg/m³]: ");
        Serial.print(massConcentrationPm4p0 / 10.0);
        Serial.println();
        Serial.print("Mass concentration pm10p0 [µg/m³]: ");
        Serial.print(massConcentrationPm10p0 / 10.0);
        Serial.println();
        Serial.print("Ambient humidity [%]: ");
        Serial.print(ambientHumidity / 100.0);
        Serial.println();
        Serial.print("Ambient temperature [°C]: ");
        Serial.print(ambientTemperature / 200.0);
        Serial.println();
        Serial.print("VOC index: ");
        Serial.print(vOCIndex);
        Serial.println();
        Serial.print("NOX index: ");
        Serial.print(nOxIndex);
        Serial.println();
        Serial.print("CO₂ [ppm]: ");
        Serial.print(cO2);
        Serial.println();
    }
}
