name: Quality check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  arduino-quality:
    uses: sensirion/.github/.github/workflows/driver.arduino.check.yml@main
    with:
      expect-arduino-examples: true
      lint-lib-manager-check: update

